### ISSUE TITLE
Most scripts are failing to run

### ISSUE THREAD

**Issue by kusold** [skatje-myers/stardewscripts#3]
```
~/stardewscripts master ruby:2.2.4 node:v6.9.2
❯ python --version
Python 2.7.12

~/stardewscripts master ruby:2.2.4 node:v6.9.2
❯ python achievement_checker.py
Choose save file [0-1]:
[0] Mike_139776628
[1] Mike_140065813
1
Traceback (most recent call last):
  File "achievement_checker.py", line 446, in <module>
    main()
  File "achievement_checker.py", line 72, in main
    print_heading('Money')
  File "achievement_checker.py", line 57, in print_heading
    hashes = '#' * n
TypeError: can't multiply sequence by non-int of type 'float'

~/stardewscripts master ruby:2.2.4 node:v6.9.2
❯ python cooking.py
  File "cooking.py", line 63
    print(GREEN + '\t' + item + ': ' + END, end='')
                                               ^
SyntaxError: invalid syntax

~/stardewscripts master ruby:2.2.4 node:v6.9.2
❯ python crafting.py
  File "crafting.py", line 64
    print(GREEN + '\t' + item + ': ' + END, end='')
                                               ^
SyntaxError: invalid syntax
```

The artifact location script does run successfully for me.

**Comment by skatje-myers** [comment]
These scripts require Python 3+.
